/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_fci_smartcornea_OpenCVEngine */

#ifndef _Included_edu_fci_smartcornea_OpenCVEngine
#define _Included_edu_fci_smartcornea_OpenCVEngine
#ifdef __cplusplus
extern "C" {
#endif
// START Face Detection

/*
 * Class:     edu_fci_smartcornea_OpenCVEngine
 * Method:    nativeCreateDetector
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeCreateDetector(JNIEnv *, jclass, jstring, jint);

/*
 * Class:     edu_fci_smartcornea_OpenCVEngine
 * Method:    nativeDestroyDetector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeDestroyDetector(JNIEnv *, jclass, jlong);

/*
 * Class:     edu_fci_smartcornea_OpenCVEngine
 * Method:    nativeStartDetector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeStartDetector(JNIEnv *, jclass, jlong);

/*
 * Class:     edu_fci_smartcornea_OpenCVEngine
 * Method:    Java_edu_fci_smartcornea_OpenCVEngine_nativeStopDetectorDetector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeStopDetector(JNIEnv *, jclass, jlong);

  /*
   * Class:     edu_fci_smartcornea_OpenCVEngine
   * Method:    nativeSetDetectorFaceSize
   * Signature: (JI)V
   */
JNIEXPORT void JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeSetDetectorFaceSize(JNIEnv *, jclass, jlong, jint);

/*
 * Class:     edu_fci_smartcornea_OpenCVEngine
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_edu_fci_smartcornea_OpenCVEngine_nativeDetect(JNIEnv *, jclass, jlong, jlong, jlong);

// END Face Detection

#ifdef __cplusplus
}
#endif
#endif
